travis:
  secure:
    BINSTAR_TOKEN: CusWFehxEFDZpubyThIL+yfBkx0zqIJUm+ADl5Vi5aTlrwg9s33iNEmY9jkM2xC4LrA+7EB0MTDqqMADRmM1ufj7lhggJoDz9EkNfzhHUTPiWWb9kxFBi38BEXwcm+AB4rJXVWMO+MYHqapDKopnVibxT3ocIvHpXgYzeVthRBK9AlVzUJ9y8yexrIC5oKXMDzOzPpQ+vtsSWtcrvOai+NiBejWefguKYx91ehzn6CunqVkyWFZkk34PrQCAGpQm93RGbXVF4PT6n9lL67Ldw9OIzYZD0/wjDHMKirUzVg+CIt/u/cOxV6F1sQ11qK5cRDkON7qAi+9WtaQVIetHwd4bAhofu9JdNwsnc9BDUyD/ebzs41R3hxLOlfTHVrIhRxzKTuYE/zJUS8MM7pwvCorVizoDU5xTci5emVoBYTqqewrwoC8HBHFhcYaGI/LWxV6mIPiZvDQXjkWNikm8gOvHk5R2PKQCcZ+5+AIZAH2wFex1GBI50T6Cx0AZPYA0e4eFIyzAkWwmYwGOKOQHPZ8XmUJMX4v3dScoBAyT2Ebmz5T3XbuHat0Dr1GkktpaJzu5EbuCxiXyCy8RvCByFJ/ftMHuhFCHF1cp4Bv6JUOC8gvIe16ZsxWTNOj92dnkE2RZiOD+Ucwcms4uwi1PRYTAMCr30ZMqxJqe5CQKUj8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
