travis:
  secure:
    BINSTAR_TOKEN: YAxuGCS2sIsN3G0xqIi/RA6C2g0ver3XmPnnbwHmbMak/7tT1Y+rIkBU7i2fwMGgdB2oOnfSicwlz5iArDeMO7vw9hXOHBOfNJXhnhG2a737fSbB9lypnEh4zAws8tXX0t1P9DgIzNl7tw8qzFjb4eOwJjVLMi1WOJoTWIJ9Zm19gkKByNFk2rWp7x8ou0Sxr7F//zlVYUPg/EdRyMPBQwz4bw1W0z7ZSOz2yK59MSbsNTyVcTKb/RLWSc6t1NerKforBe08ArS1PDCmPY+go0BHaqaXGeH4IgJBhrlalbhEfyYwNGWtVB5aGyvp+ciJWvZkii7yychYR2SOMMYUbsoU26j84BmtCsU+KOsbt0OKGaV5p+sWOOjE2pooltSRqTQ1hDM3RWmY2B8HelYgw15LInBNim0bv/3vop9r3negYPlZkvZaYqwM0bVIlL+t1pY0ifJQfZZ0KbjVe26fnvpQilmiLloCuonatsbb4NOw13e5oUoSvMVVuiWpoLO8LsT/fA+/6GpfS54xOZl89hRKOjEptR0hQkq1CNoEIOXhQP85jDa0sDP/tTKQBrQ2y8mYPiuruh95O8bZn148h3CGG9LvC3MTf+s4gGPXHvK3ozWhlZ9fyQ5A4/kMsbscdJ2RRTlrVccYmeKJjDYsFiEbaJhP822efURI1po1st4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
